### ISSUE TITLE
AddressSanitizer Results

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-crypto#124]
```
=================================================================
==12714==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffeb5e4141f at pc 0x557118e3a63e bp 0x7ffeb5e411c0 sp 0x7ffeb5e40970
READ of size 22 at 0x7ffeb5e4141f thread T0
    #0 0x557118e3a63d in __asan_memcpy (test_check+0x15863d)
    #1 0x557118f64f97 in sha256_Update sha2.c:916:3
    #2 0x557118f6dfa9 in hasher_Update hasher.c:45:3
    #3 0x557118f6dfa9 in hasher_Raw hasher.c:73
    #4 0x557118f585ac in b58check base58.c:133:2
    #5 0x557118f585ac in base58_decode_check base58.c:218
    #6 0x557118f4a0dc in ecdsa_address_decode ecdsa.c:951:9
    #7 0x557118ee9ad8 in test_address_decode test_check.c:2954:8
    #8 0x7f64fb7b4cb7 in srunner_run_tagged (/usr/lib/libcheck.so.0+0x5cb7)
    #9 0x557118f29bdf in main test_check.c:4626:2
    #10 0x7f64fa88af49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #11 0x557118d90b49 in _start (test_check+0xaeb49)

Address 0x7ffeb5e4141f is located in stack of thread T0 at offset 447 in frame
    #0 0x557118f6de2f in hasher_Raw hasher.c:69

  This frame has 1 object(s):
    [32, 168) 'hasher' (line 70) <== Memory access at offset 447 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow (test_check+0x15863d) in __asan_memcpy
Shadow bytes around the buggy address:
  0x100056bc0230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056bc0240: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x100056bc0250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056bc0260: 00 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x100056bc0270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100056bc0280: ca ca ca[ca]00 00 00 01 cb cb cb cb f1 f1 f1 f1
  0x100056bc0290: 00 00 00 00 f2 f2 f2 f2 00 f3 f3 f3 00 00 00 00
  0x100056bc02a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056bc02b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100056bc02c0: f1 f1 f1 f1 00 00 00 00 00 04 f2 f2 f2 f2 f8 f8
  0x100056bc02d0: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==12714==ABORTING
```

**Comment by prusnak** [comment]
I believe this has been fixed via #141, please reopen if I am wrong.
